[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SDMO"
version = "0.1.0"
dynamic = ["dependencies"]

[tool.setuptools]
packages = ["tools", "evaluators", "tests"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}